// This module is generated by `script/`.

export type Constant =
  | 2
  | 1
  | 6
  | 63
  | 32
  | 'CDATA['
  | 2
  | 1
  | 7
  | 6
  | 31
  | 3
  | 'content'
  | 'flow'
  | 'string'
  | 'text'
  | 2
  | 6
  | 5
  | 2
  | 7
  | 4
  | 3
  | 1
  | 8
  | 999
  | 3
  | 10
  | 10
  | 16
  | 4
  | 3
  | 10000

// @for-script: REMOVE_ALL_THING_BELOW

export interface Constants {
  attentionSideAfter: 2
  attentionSideBefore: 1
  atxHeadingOpeningFenceSizeMax: 6
  autolinkDomainSizeMax: 63
  autolinkSchemeSizeMax: 32
  cdataOpeningString: 'CDATA['
  characterGroupPunctuation: 2
  characterGroupWhitespace: 1
  characterReferenceDecimalSizeMax: 7
  characterReferenceHexadecimalSizeMax: 6
  characterReferenceNamedSizeMax: 31
  codeFencedSequenceSizeMin: 3
  contentTypeContent: 'content'
  contentTypeFlow: 'flow'
  contentTypeString: 'string'
  contentTypeText: 'text'
  hardBreakPrefixSizeMin: 2
  htmlBasic: 6
  htmlCdata: 5
  htmlComment: 2
  htmlComplete: 7
  htmlDeclaration: 4
  htmlInstruction: 3
  htmlRaw: 1
  htmlRawSizeMax: 8
  linkReferenceSizeMax: 999
  linkResourceDestinationBalanceMax: 3
  listItemValueSizeMax: 10
  numericBaseDecimal: 10
  numericBaseHexadecimal: 16
  tabSize: 4
  thematicBreakMarkerCountMin: 3
  v8MaxSafeChunkSize: 10000
}

declare const value: Constants

export default value
