// This module is compiled away!
exports.asciiAlphaCaseDifference = 32 // The shift between lower- and uppercase is `0x20`.
exports.characterGroupWhitespace = 1 // Symbol used to indicate a character is whitespace
exports.characterGroupPunctuation = 2 // Symbol used to indicate a character is whitespace
exports.cdataOpeningString = 'CDATA[' // And preceded by `<![`.
exports.attentionSideBefore = 1 // Symbol to mark an attention sequence as before content: `*a`
exports.attentionSideAfter = 2 // Symbol to mark an attention sequence as after content: `a*`
exports.htmlRaw = 1 // Symbol for `<script>`
exports.htmlComment = 2 // Symbol for `<!---->`
exports.htmlInstruction = 3 // Symbol for `<?php?>`
exports.htmlDeclaration = 4 // Symbol for `<!doctype>`
exports.htmlCdata = 5 // Symbol for `<![CDATA[]]>`
exports.htmlBasic = 6 // Symbol for `<div`
exports.htmlComplete = 7 // Symbol for `<x>`
exports.maxAutolinkDomainSize = 63 // 63 characters is fine, 64 is too many.
exports.maxAutolinkSchemeSize = 32 // 32 characters is fine, 33 is too many.
exports.maxAtxHeadingOpeningFenceSize = 6 // 6 number signs is fine, 7 isn’t.
exports.maxCharacterReferenceDecimalSize = 7 // `&#9999999;`.
exports.maxCharacterReferenceHexadecimalSize = 6 // `&#xff9999;`.
exports.maxCharacterReferenceNamedSize = 31 // `&CounterClockwiseContourIntegral;`.
exports.minHardBreakSize = 2 // At least 2 trailing spaces are needed.
exports.minCodeFencedFenceSize = 3 // At least 3 ticks or tildes are needed.
exports.minThematicBreakMarkerCount = 3 // At least 3 asterisks, dashes, or underscores are needed.
exports.numericBaseDecimal = 10
exports.numericBaseHexadecimal = 0x10
exports.tabSize = 4 // Tabs have a hard-coded size of 4, per CommonMark.
