// This module is compiled away!
exports.tabSize = 4 // Tabs have a hard-coded size of 4, per CommonMark.
exports.cdataOpeningString = 'CDATA[' // And preceded by `<![`.
exports.kindHtmlRaw = 1 // `<script>`
exports.kindHtmlComment = 2 // `<!---->`
exports.kindHtmlInstruction = 3 // `<?php?>`
exports.kindHtmlDeclaration = 4 // `<!doctype>`
exports.kindHtmlCdata = 5 // `<![CDATA[]]>`
exports.kindHtmlBasic = 6 // `<div`
exports.kindHtmlComplete = 7 // `<x>`
exports.maxAtxHeadingOpeningFenceSize = 6 // 6 number signs is fine, 7 isn’t.
exports.maxAutolinkDomainSize = 63 // 63 characters is fine, 64 is too many.
exports.maxCharacterReferenceDecimalSize = 7 // `&#9999999;`.
exports.maxCharacterReferenceHexadecimalSize = 6 // `&#xff9999;`.
exports.maxCharacterReferenceNamedSize = 31 // `&CounterClockwiseContourIntegral;`.
exports.minHardBreakSize = 2 // At least 2 trailing spaces are needed.
exports.minFencedCodeFenceSize = 3 // At least 3 ticks or tildes are needed.
exports.minThematicBreakMarkerCount = 3 // At least 3 asterisks, dashes, or underscores are needed.
exports.numericBaseDecimal = 10
exports.numericBaseHexadecimal = 0x10
exports.emphasisSideBefore = 1 // Symbol to mark an emphasis sequence as before content: `*a`
exports.emphasisSideAfter = 2 // Symbol to mark an emphasis sequence as after content: `a*`
exports.characterGroupWhitespace = 1 // Symbol used to indicate a character is whitespace
exports.characterGroupPunctuation = 2 // Symbol used to indicate a character is whitespace
