// This module is compiled away!
export const asciiAlphaCaseDifference = 32 // The shift between lower- and uppercase is `0x20`.
export const attentionSideBefore = 1 // Symbol to mark an attention sequence as before content: `*a`
export const attentionSideAfter = 2 // Symbol to mark an attention sequence as after content: `a*`
export const atxHeadingOpeningFenceSizeMax = 6 // 6 number signs is fine, 7 isn’t.
export const autolinkDomainSizeMax = 63 // 63 characters is fine, 64 is too many.
export const autolinkSchemeSizeMax = 32 // 32 characters is fine, 33 is too many.
export const cdataOpeningString = 'CDATA[' // And preceded by `<![`.
export const characterGroupWhitespace = 1 // Symbol used to indicate a character is whitespace
export const characterGroupPunctuation = 2 // Symbol used to indicate a character is whitespace
export const characterReferenceDecimalSizeMax = 7 // `&#9999999;`.
export const characterReferenceHexadecimalSizeMax = 6 // `&#xff9999;`.
export const characterReferenceNamedSizeMax = 31 // `&CounterClockwiseContourIntegral;`.
export const codeFencedSequenceSizeMin = 3 // At least 3 ticks or tildes are needed.
export const contentTypeFlow = 'flow'
export const contentTypeContent = 'content'
export const contentTypeString = 'string'
export const contentTypeText = 'text'
export const hardBreakPrefixSizeMin = 2 // At least 2 trailing spaces are needed.
export const htmlRaw = 1 // Symbol for `<script>`
export const htmlComment = 2 // Symbol for `<!---->`
export const htmlInstruction = 3 // Symbol for `<?php?>`
export const htmlDeclaration = 4 // Symbol for `<!doctype>`
export const htmlCdata = 5 // Symbol for `<![CDATA[]]>`
export const htmlBasic = 6 // Symbol for `<div`
export const htmlComplete = 7 // Symbol for `<x>`
export const htmlRawSizeMax = 6 // Length of `script`.
export const linkResourceDestinationBalanceMax = 3 // See: <https://spec.commonmark.org/0.29/#link-destination>
export const linkReferenceSizeMax = 999 // See: <https://spec.commonmark.org/0.29/#link-label>
export const listItemValueSizeMax = 10 // See: <https://spec.commonmark.org/0.29/#ordered-list-marker>
export const numericBaseDecimal = 10
export const numericBaseHexadecimal = 0x10
export const tabSize = 4 // Tabs have a hard-coded size of 4, per CommonMark.
export const thematicBreakMarkerCountMin = 3 // At least 3 asterisks, dashes, or underscores are needed.
