import fs from 'fs'
import path from 'path'
import regenerate from 'regenerate'
import codes from '../lib/character/codes'

var pcAll = regenerate()
  .addRange(codes.exclamationMark, codes.slash)
  .addRange(codes.colon, codes.atSign)
  .addRange(codes.leftSquareBracket, codes.graveAccent)
  .addRange(codes.leftCurlyBrace, codes.tilde)
  .add(unicode('Connector_Punctuation'))
  .add(unicode('Dash_Punctuation'))
  .add(unicode('Close_Punctuation'))
  .add(unicode('Final_Punctuation'))
  .add(unicode('Initial_Punctuation'))
  .add(unicode('Other_Punctuation'))
  .add(unicode('Open_Punctuation'))
  .valueOf()

// Note: we don’t support astrals.
var pc = regenerate()
  .add(
    pcAll.filter(function (d: any) {
      return d <= 0xffff
    })
  )
  .toRegExp()

fs.writeFileSync(
  path.join('lib', 'constant', 'unicode-punctuation-regex.js'),
  '// This module is generated by `script/`.\nmodule.exports = ' + pc + '\n'
)

function unicode(d: any) {
  return require('unicode-13.0.0/General_Category/' + d + '/code-points')
}
