name: canary
on:
  - pull_request
  - push
jobs:
  canary:
    name: testing ${{matrix.package}}
    runs-on: ${{matrix.os}}
    steps:
      - name: checkout micromark
        uses: actions/checkout@v2
      - name: setup node
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{matrix.node}}
      - name: setup micromark
        run: |
          npm install -g npm
          npm install
          npm run build
      - name: checkout ${{matrix.package}}
        uses: actions/checkout@v2
        with:
          repository: ${{matrix.package}}
          path: canary/${{matrix.package}}
      - name: test ${{matrix.package}}
        run: |
          npm install
          for package in $(ls ../../packages); do
            npx rimraf "node_modules/**/$package"
          done
          npm test
        working-directory: canary/${{matrix.package}}

    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        os:
          - ubuntu-latest
        node:
          - node
        package:
          - micromark/micromark-extension-gfm
          - micromark/micromark-extension-directive
          - micromark/micromark-extension-mdx
          - syntax-tree/mdast-util-from-markdown
          - remarkjs/remark
          - remarkjs/react-markdown
